"""List of Computer Science Internships"""
csList = [
    ["Google", "Software Engineering Intern", "Remote", "https://careers.google.com/students/"]
    ["NASA Jet Propulsion Laboratory", "Software Engineer Intern", "Pasadena, CA", "https://www.jpl.nasa.gov/edu/intern/"]
    ["Riot Games", "Software Engineering Intern", "Los Angeles, CA", "https://www.riotgames.com/en/jobs"]
    ["Disney Technology", "Software Development Intern", "Burbank, CA", "https://jobs.disneycareers.com/"]
    ["Snap Inc.", "Software Engineer Intern", "Venice, CA", "https://snap.com/en-US/jobs/"]
    ["Northrop Grumman", "Software Engineering Intern", "Various locations in LA County", "https://www.northropgrumman.com/careers/"]
    ["SpaceX", "Software Engineer Intern", "Hawthorne, CA", "https://www.spacex.com/careers/"]
    ["Los Angeles County Department of Public Health", "IT Intern", "Los Angeles, CA", "http://publichealth.lacounty.gov/"]
    ["Kaiser Permanente", "IT Intern", "Los Angeles, CA", "https://www.kaiserpermanentejobs.org/"]
    ["Broadcom Inc.", "Software Engineering Intern", "Irvine, CA", "https://www.broadcom.com/company/careers"]
    ["Ingram Micro", "Software Development Intern", "Irvine, CA", "https://careers.ingrammicro.com/"]
    ["Riot Games", "Software Engineering Intern", "Anaheim, CA", "https://www.riotgames.com/en/jobs"]
    ["NVIDIA", "Software Engineering Intern", "Santa Ana, CA", "https://www.nvidia.com/en-us/about-nvidia/careers/"]
    ["Honeywell", "Software Engineering Intern", "Anaheim, CA", "https://careers.honeywell.com/us/en"]
    ["Western Digital", "Software Engineering Intern", "Irvine, CA", "https://careers.westerndigital.com/"]
    ["The Walt Disney Company", "Technology Intern", "Anaheim, CA", "https://jobs.disneycareers.com/"]
    ["Amazon", "Software Development Intern", "Irvine, CA", "https://www.amazon.jobs/en/"]
    ["Marvell Technology", "Software Engineering Intern", "Irvine, CA", "https://www.marvell.com/careers/"]
]

"""List of Electricl Engineer Internships"""
eeList = [
    ["Northrop Grumman", "Electrical Engineering Intern", "Redondo Beach, CA", "https://www.northropgrumman.com/careers/"]
    ["NASA Jet Propulsion Laboratory", "Electrical Engineer Intern", "Pasadena, CA", "https://www.jpl.nasa.gov/edu/intern/"]
    ["Raytheon Technologies", "Electrical Engineering Intern", "El Segundo, CA", "https://jobs.raytheon.com/"]
    ["SpaceX", "Electrical Engineering Intern", "Hawthorne, CA", "https://www.spacex.com/careers/"]
    ["General Atomics", "Electrical Engineering Intern", "San Diego, CA (near LA County)", "https://www.ga.com/careers"]
    ["Los Angeles Department of Water and Power", "Electrical Engineering Intern", "Los Angeles, CA", "https://www.ladwp.com/"]
    ["Boeing", "Electrical Engineering Intern", "Long Beach, CA", "https://jobs.boeing.com/"]
    ["L3Harris Technologies", "Electrical Engineering Intern", "Los Angeles, CA", "https://careers.l3harris.com/"]
    ["Kaiser Permanente", "Electrical Engineering Intern", "Los Angeles, CA", "https://www.kaiserpermanentejobs.org/"]
    ["California Institute of Technology (Caltech)", "Electrical Engineering Intern", "Pasadena, CA", "https://www.caltech.edu/careers"]
    ["Broadcom Inc.", "Software Engineering Intern", "Irvine, CA", "https://www.broadcom.com/company/careers"]
    ["Ingram Micro", "Software Development Intern", "Irvine, CA", "https://careers.ingrammicro.com/"]
    ["Riot Games", "Software Engineering Intern", "Anaheim, CA", "https://www.riotgames.com/en/jobs"]
    ["NVIDIA", "Software Engineering Intern", "Santa Ana, CA", "https://www.nvidia.com/en-us/about-nvidia/careers/"]
    ["Honeywell", "Software Engineering Intern", "Anaheim, CA", "https://careers.honeywell.com/us/en"]
    ["Western Digital", "Software Engineering Intern", "Irvine, CA", "https://careers.westerndigital.com/"]
    ["The Walt Disney Company", "Technology Intern", "Anaheim, CA", "https://jobs.disneycareers.com/"]
    ["Amazon", "Software Development Intern", "Irvine, CA", "https://www.amazon.jobs/en/"]
    ["Marvell Technology", "Software Engineering Intern", "Irvine, CA", "https://www.marvell.com/careers/"]
]

"""List of civil Engineer Internships"""
ceList = [
    ["AECOM", "Civil Engineering Intern", "Los Angeles, CA", "https://www.aecom.com/careers/"]
    ["WSP USA", "Civil Engineering Intern", "Los Angeles, CA", "https://www.wsp.com/en-US/careers"]
    ["Jacobs", "Civil Engineering Intern", "Los Angeles, CA", "https://www.jacobs.com/careers"]
    ["Caltrans", "Civil Engineering Intern", "Los Angeles, CA", "https://dot.ca.gov/"]
    ["Kimley-Horn", "Civil Engineering Intern", "Los Angeles, CA", "https://www.kimley-horn.com/careers/"]
    ["HDR", "Civil Engineering Intern", "Los Angeles, CA", "https://www.hdrinc.com/careers"]
    ["Tetra Tech", "Civil Engineering Intern", "Los Angeles, CA", "https://www.tetratech.com/en/careers"]
    ["Los Angeles County Department of Public Works", "Civil Engineering Intern", "Los Angeles, CA", "http://dpw.lacounty.gov/"]
    ["Mott MacDonald", "Civil Engineering Intern", "Los Angeles, CA", "https://www.mottmac.com/careers"]
    ["SNC-Lavalin", "Civil Engineering Intern", "Los Angeles, CA", "https://www.snclavalin.com/en/careers"]
    ["AECOM", "Civil Engineering Intern", "Irvine, CA", "https://www.aecom.com/careers/"]
    ["WSP USA", "Civil Engineering Intern", "Orange, CA", "https://www.wsp.com/en-US/careers"]
    ["Jacobs", "Civil Engineering Intern", "Santa Ana, CA", "https://www.jacobs.com/careers"]
    ["Kimley-Horn", "Civil Engineering Intern", "Irvine, CA", "https://www.kimley-horn.com/careers/"]
    ["Mott MacDonald", "Civil Engineering Intern", "Irvine, CA", "https://www.mottmac.com/careers"]
    ["Tetra Tech", "Civil Engineering Intern", "Costa Mesa, CA", "https://www.tetratech.com/en/careers"]
    ["Orange County Public Works", "Civil Engineering Intern", "Orange, CA", "https://www.ocpw.ocgov.com/"]
    ["Los Angeles Department of Water and Power", "Civil Engineering Intern", "Irvine, CA", "https://www.ladwp.com/"]
    ["PCL Construction", "Civil Engineering Intern", "Irvine, CA", "https://www.pcl.com/en/careers"]
    ["Civiltec Engineering", "Civil Engineering Intern", "Lake Forest, CA", "https://civiltec.com/careers/"]
]

"""List of Mechanical Engineer Internships"""
meList = [
    ["Northrop Grumman", "Mechanical Engineering Intern", "Redondo Beach, CA", "https://www.northropgrumman.com/careers/"]
    ["NASA Jet Propulsion Laboratory", "Mechanical Engineer Intern", "Pasadena, CA", "https://www.jpl.nasa.gov/edu/intern/"]
    ["SpaceX", "Mechanical Engineering Intern", "Hawthorne, CA", "https://www.spacex.com/careers/"]
    ["Raytheon Technologies", "Mechanical Engineering Intern", "El Segundo, CA", "https://jobs.raytheon.com/"]
    ["Boeing", "Mechanical Engineering Intern", "Long Beach, CA", "https://jobs.boeing.com/"]
    ["California Institute of Technology (Caltech)", "Mechanical Engineering Intern", "Pasadena, CA", "https://www.caltech.edu/careers"]
    ["Kaiser Permanente", "Mechanical Engineering Intern", "Los Angeles, CA", "https://www.kaiserpermanentejobs.org/"]
    ["Honeywell", "Mechanical Engineering Intern", "Los Angeles, CA", "https://careers.honeywell.com/us/en"]
    ["L3Harris Technologies", "Mechanical Engineering Intern", "Los Angeles, CA", "https://careers.l3harris.com/"]
    ["Sierra Nevada Corporation", "Mechanical Engineering Intern", "Los Angeles, CA", "https://www.sncorp.com/careers/"]
    ["Northrop Grumman", "Mechanical Engineering Intern", "Irvine, CA", "https://www.northropgrumman.com/careers/"]
    ["Boeing", "Mechanical Engineering Intern", "Seal Beach, CA", "https://jobs.boeing.com/"]
    ["Raytheon Technologies", "Mechanical Engineering Intern", "Fullerton, CA", "https://jobs.raytheon.com/"]
    ["General Motors", "Mechanical Engineering Intern", "Tustin, CA", "https://search.gm.com/"]
    ["Kaiser Permanente", "Mechanical Engineering Intern", "Anaheim, CA", "https://www.kaiserpermanentejobs.org/"]
    ["NVIDIA", "Mechanical Engineering Intern", "Santa Ana, CA", "https://www.nvidia.com/en-us/about-nvidia/careers/"]
    ["Medtronic", "Mechanical Engineering Intern", "Irvine, CA", "https://www.medtronic.com/us-en/careers.html"]
    ["L3Harris Technologies", "Mechanical Engineering Intern", "Irvine, CA", "https://careers.l3harris.com/"]
    ["Parker Hannifin", "Mechanical Engineering Intern", "Irvine, CA", "https://www.parker.com/careers/"]
    ["Teledyne Technologies", "Mechanical Engineering Intern", "Tustin, CA", "https://www.teledyne.com/careers"]
]

"""List of Business Internships"""
businessList = [
    ["Google", "Business Intern", "Los Angeles, CA", "https://careers.google.com/students/"]
    ["Disney", "Business Analyst Intern", "Burbank, CA", "https://jobs.disneycareers.com/"]
    ["Amazon", "Business Development Intern", "Los Angeles, CA", "https://www.amazon.jobs/en/"]
    ["Snap Inc.", "Marketing Intern", "Venice, CA", "https://snap.com/en-US/jobs/"]
    ["Warner Bros.", "Business Affairs Intern", "Burbank, CA", "https://www.warnerbroscareers.com/"]
    ["Kaiser Permanente", "Business Operations Intern", "Los Angeles, CA", "https://www.kaiserpermanentejobs.org/"]
    ["Northrop Grumman", "Business Management Intern", "Redondo Beach, CA", "https://www.northropgrumman.com/careers/"]
    ["Sony Pictures", "Business Operations Intern", "Culver City, CA", "https://www.sonypictures.com/corp/careers.html"]
    ["AECOM", "Business Development Intern", "Los Angeles, CA", "https://www.aecom.com/careers/"]
    ["L3Harris Technologies", "Business Analyst Intern", "Los Angeles, CA", "https://careers.l3harris.com/"]
    ["Broadcom Inc.", "Business Analyst Intern", "Irvine, CA", "https://www.broadcom.com/company/careers"]
    ["Ingram Micro", "Marketing Intern", "Irvine, CA", "https://careers.ingrammicro.com/"]
    ["Kaiser Permanente", "Business Operations Intern", "Anaheim, CA", "https://www.kaiserpermanentejobs.org/"]
    ["Amazon", "Business Development Intern", "Irvine, CA", "https://www.amazon.jobs/en/"]
    ["Ultimate Software", "Business Analyst Intern", "Irvine, CA", "https://www.ultimatesoftware.com/careers"]
    ["Walt Disney Company", "Business Intern", "Anaheim, CA", "https://jobs.disneycareers.com/"]
    ["Parker Hannifin", "Business Development Intern", "Irvine, CA", "https://www.parker.com/careers/"]
    ["L3Harris Technologies", "Business Analyst Intern", "Irvine, CA", "https://careers.l3harris.com/"]
    ["Tetra Tech", "Business Intern", "Costa Mesa, CA", "https://www.tetratech.com/en/careers"]
    ["Medtronic", "Business Operations Intern", "Irvine, CA", "https://www.medtronic.com/us-en/careers.html"]
]

"""List of Accounting Internships"""
accountingList = [
    ["Deloitte", "Audit Intern", "Los Angeles, CA", "https://www2.deloitte.com/us/en/pages/careers/topics/join-deloitte.html"]
    ["KPMG", "Audit Intern", "Los Angeles, CA", "https://home.kpmg/xx/en/home/careers/students.html"]
    ["EY", "Assurance Intern", "Los Angeles, CA", "https://www.ey.com/en_us/careers/students"]
    ["PwC", "Tax Intern", "Los Angeles, CA", "https://www.pwc.com/gx/en/careers/students.html"]
    ["Grant Thornton", "Audit Intern", "Los Angeles, CA", "https://www.grantthornton.com/careers/students.aspx"]
    ["BDO USA", "Tax Intern", "Los Angeles, CA", "https://www.bdo.com/careers"]
    ["RSM US LLP", "Audit Intern", "Los Angeles, CA", "https://rsmus.com/careers/students.html"]
    ["Tetra Tech", "Accounting Intern", "Los Angeles, CA", "https://www.tetratech.com/en/careers"]
    ["California State Auditor", "Accounting Intern", "Los Angeles, CA", "https://www.auditor.ca.gov/"]
    ["H&R Block", "Tax Intern", "Los Angeles, CA", "https://www.hrblock.com/careers/"]
    ["KPMG", "Audit Intern", "Irvine, CA", "https://home.kpmg/xx/en/home/careers/students.html"]
    ["Deloitte", "Audit Intern", "Costa Mesa, CA", "https://www2.deloitte.com/us/en/pages/careers/topics/join-deloitte.html"]
    ["Grant Thornton", "Tax Intern", "Irvine, CA", "https://www.grantthornton.com/careers/students.aspx"]
    ["RSM US LLP", "Audit Intern", "Irvine, CA", "https://rsmus.com/careers/students.html"]
    ["BDO USA", "Tax Intern", "Irvine, CA", "https://www.bdo.com/careers"]
    ["Moss Adams", "Audit Intern", "Irvine, CA", "https://www.mossadams.com/careers"]
    ["California State University, Fullerton", "Accounting Intern", "Fullerton, CA", "https://www.fullerton.edu/career/"]
    ["Medtronic", "Accounting Intern", "Irvine, CA", "https://www.medtronic.com/us-en/careers.html"]
    ["Tetra Tech", "Accounting Intern", "Costa Mesa, CA", "https://www.tetratech.com/en/careers"]
    ["H&R Block", "Tax Intern", "Orange, CA", "https://www.hrblock.com/careers/"]
]

"""List of Communication Internships"""
communicationList = [
    ["Disney", "Public Relations Intern", "Burbank, CA", "https://jobs.disneycareers.com/"]
    ["Sony Pictures", "Marketing Intern", "Culver City, CA", "https://www.sonypictures.com/corp/careers.html"]
    ["Warner Bros.", "Communications Intern", "Burbank, CA", "https://www.warnerbroscareers.com/"]
    ["NBCUniversal", "Communications Intern", "Universal City, CA", "https://www.nbcunicareers.com/"]
    ["Los Angeles Times", "Editorial Intern", "Los Angeles, CA", "https://www.latimes.com/about/careers"]
    ["Snap Inc.", "Social Media Intern", "Venice, CA", "https://snap.com/en-US/jobs/"]
    ["Paramount Pictures", "Marketing Intern", "Hollywood, CA", "https://www.paramount.com/careers"]
    ["Cal State LA", "Communication Intern", "Los Angeles, CA", "https://www.calstatela.edu/"]
    ["American Red Cross", "Marketing and Communications Intern", "Los Angeles, CA", "https://www.redcross.org/about-us/careers.html"]
    ["UCLA", "Communications Intern", "Los Angeles, CA", "https://www.ucla.edu/careers"]
    ["Broadcom Inc.", "Communications Intern", "Irvine, CA", "https://www.broadcom.com/company/careers"]
    ["Ingram Micro", "Marketing Intern", "Irvine, CA", "https://careers.ingrammicro.com/"]
    ["Kaiser Permanente", "Communications Intern", "Anaheim, CA", "https://www.kaiserpermanentejobs.org/"]
    ["Medtronic", "Communications Intern", "Irvine, CA", "https://www.medtronic.com/us-en/careers.html"]
    ["The Walt Disney Company", "Public Relations Intern", "Anaheim, CA", "https://jobs.disneycareers.com/"]
    ["Parker Hannifin", "Marketing Communications Intern", "Irvine, CA", "https://www.parker.com/careers/"]
    ["Blizzard Entertainment", "Communications Intern", "Irvine, CA", "https://careers.blizzard.com/"]
    ["Kia Motors", "Corporate Communications Intern", "Irvine, CA", "https://www.kia.com/us/en/company/careers"]
    ["Southern California Edison", "Communications Intern", "Rosemead, CA", "https://www.sce.com/careers"]
    ["Orange County Register", "Editorial Intern", "Santa Ana, CA", "https://www.ocregister.com/careers"]
]
